INFO:waitress:Serving on http://0.0.0.0:6789
INFO:waitress:Serving on http://0.0.0.0:6789
INFO:waitress:Serving on http://0.0.0.0:6789
INFO:waitress:Serving on http://0.0.0.0:6789
INFO:waitress:Serving on http://0.0.0.0:6789
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
INFO:waitress:Serving on http://0.0.0.0:6789
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
INFO:waitress:Serving on http://0.0.0.0:6789
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
INFO:waitress:Serving on http://0.0.0.0:6789
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
ERROR:server:Exception on /help [GET]
Traceback (most recent call last):
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/home/enviwork/.local/lib/python3.8/site-packages/flask/app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'get_help' did not return a valid response. The function either returned None or ended without a return statement.
